### ISSUE TITLE
ErrorCode: CE_1040 | QRadar v1.2.1

### ISSUE THREAD

**Issue by tpimpao** [netskopeoss/ta_cloud_exchange_plugins#37]
Hi,
I just installed the last version of Netskope CE;

Core Version	:	3.4.0
UI Version	:	3.4.0
Database Version	:	3.4.0

The integration with QRadar if failing with the CE_1040 error code:

Stacktrace:

```
326a1dfbbec [2022-09-23 14:55:31,675: INFO/ForkPoolWorker-4] Task common.pull_alerts[1ea33a25-6a95-4230-85d7-95921841983f] succeeded in 0.3529977950001921s: {'success': False, 'message': 'HTTPError(\'Error occurred while pulling alerts.\')', 'trace': 'Traceback (most recent call last):
2326a1dfbbec   File "/opt/netskope/common/utils/alerts_helper.py", line 229, in get_alerts
2326a1dfbbec     f"Error occurred while pulling alerts. {response.text}"
2326a1dfbbec AttributeError: \'dict\' object has no attribute \'text\'
2326a1dfbbec
2326a1dfbbec During handling of the above exception, another exception occurred:
2326a1dfbbec
2326a1dfbbec Traceback (most recent call last):
2326a1dfbbec   File "/opt/netskope/common/utils/task_decorator.py", line 61, in wrapper
2326a1dfbbec     ret = func(*args, **kwargs)
2326a1dfbbec   File "/opt/netskope/common/celery/pull_alerts.py", line 70, in pull_alerts
2326a1dfbbec     for alerts in alerts_helper.load(tenant):
2326a1dfbbec   File "/opt/netskope/common/utils/alerts_helper.py", line 50, in load
2326a1dfbbec     yield from self.get_alerts(start_time, end_time)
2326a1dfbbec   File "/opt/netskope/common/utils/alerts_helper.py", line 276, in get_alerts
2326a1dfbbec     raise requests.HTTPError(
2326a1dfbbec requests.exceptions.HTTPError: Error occurred while pulling alerts.
2326a1dfbbec '}
2326a1dfbbec [2022-09-23 14:55:32,700: INFO/ForkPoolWorker-1] Task cls.execute_historical[4e823df7-4bba-44b8-86f6-f9cc1f9bfc86] succeeded in 1.0894251099998655s: {'success': True, 'message': 'No alerts need to be pulled.'}

```

Thanks
TP

**Comment by tpimpao** [comment]
Change the collector endpoint from QRadar fix the erro.
